/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as PainelNovoRouteImport } from './routes/painel.novo'
import { Route as PainelImoveisRouteImport } from './routes/painel.imoveis'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'
import { Route as PainelEditarIdRouteImport } from './routes/painel.editar.$id'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImoveisRoute,
} as any)
const PainelNovoRoute = PainelNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => PainelRoute,
} as any)
const PainelImoveisRoute = PainelImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => PainelRoute,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ImoveisRoute,
} as any)
const PainelEditarIdRoute = PainelEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/painel': typeof PainelRouteWithChildren
  '/imoveis/$id': typeof ImoveisIdRoute
  '/painel/imoveis': typeof PainelImoveisRoute
  '/painel/novo': typeof PainelNovoRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/editar/$id': typeof PainelEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/painel/imoveis': typeof PainelImoveisRoute
  '/painel/novo': typeof PainelNovoRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/painel': typeof PainelIndexRoute
  '/painel/editar/$id': typeof PainelEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/painel': typeof PainelRouteWithChildren
  '/imoveis/$id': typeof ImoveisIdRoute
  '/painel/imoveis': typeof PainelImoveisRoute
  '/painel/novo': typeof PainelNovoRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/editar/$id': typeof PainelEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/entrar'
    | '/imoveis'
    | '/painel'
    | '/imoveis/$id'
    | '/painel/imoveis'
    | '/painel/novo'
    | '/imoveis/'
    | '/painel/'
    | '/painel/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/entrar'
    | '/imoveis/$id'
    | '/painel/imoveis'
    | '/painel/novo'
    | '/imoveis'
    | '/painel'
    | '/painel/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/entrar'
    | '/imoveis'
    | '/painel'
    | '/imoveis/$id'
    | '/painel/imoveis'
    | '/painel/novo'
    | '/imoveis/'
    | '/painel/'
    | '/painel/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/painel/novo': {
      id: '/painel/novo'
      path: '/novo'
      fullPath: '/painel/novo'
      preLoaderRoute: typeof PainelNovoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/imoveis': {
      id: '/painel/imoveis'
      path: '/imoveis'
      fullPath: '/painel/imoveis'
      preLoaderRoute: typeof PainelImoveisRouteImport
      parentRoute: typeof PainelRoute
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/painel/editar/$id': {
      id: '/painel/editar/$id'
      path: '/editar/$id'
      fullPath: '/painel/editar/$id'
      preLoaderRoute: typeof PainelEditarIdRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface ImoveisRouteChildren {
  ImoveisIdRoute: typeof ImoveisIdRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisIdRoute: ImoveisIdRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

interface PainelRouteChildren {
  PainelImoveisRoute: typeof PainelImoveisRoute
  PainelNovoRoute: typeof PainelNovoRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelEditarIdRoute: typeof PainelEditarIdRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelImoveisRoute: PainelImoveisRoute,
  PainelNovoRoute: PainelNovoRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelEditarIdRoute: PainelEditarIdRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
  PainelRoute: PainelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
